---

- name:       Generating Netplan Configuration
  command:    netplan generate
  listen:     netplan generate config
  notify:     netplan apply config

- name:       Applying Netplan Configuration
  command:    netplan apply
  async:      0
  poll:       0
  ignore_errors: true
  listen:     netplan apply config
  when:       netplan_apply
